var annotated_dup =
[
    [ "ImpactCFX", "namespace_impact_c_f_x.html", [
      [ "Audio", "namespace_impact_c_f_x_1_1_audio.html", [
        [ "AudioEffect", "struct_impact_c_f_x_1_1_audio_1_1_audio_effect.html", "struct_impact_c_f_x_1_1_audio_1_1_audio_effect" ],
        [ "AudioEffectResult", "struct_impact_c_f_x_1_1_audio_1_1_audio_effect_result.html", "struct_impact_c_f_x_1_1_audio_1_1_audio_effect_result" ],
        [ "AudioPool", "class_impact_c_f_x_1_1_audio_1_1_audio_pool.html", null ],
        [ "ImpactAudioEffectAuthoring", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_effect_authoring.html", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_effect_authoring" ],
        [ "ImpactAudioEffectProcessor", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_effect_processor.html", null ],
        [ "ImpactAudioSource", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_source.html", null ],
        [ "ImpactAudioSourceBase", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_source_base.html", "class_impact_c_f_x_1_1_audio_1_1_impact_audio_source_base" ]
      ] ],
      [ "Decals", "namespace_impact_c_f_x_1_1_decals.html", [
        [ "DecalEffect", "struct_impact_c_f_x_1_1_decals_1_1_decal_effect.html", "struct_impact_c_f_x_1_1_decals_1_1_decal_effect" ],
        [ "DecalEffectResult", "struct_impact_c_f_x_1_1_decals_1_1_decal_effect_result.html", "struct_impact_c_f_x_1_1_decals_1_1_decal_effect_result" ],
        [ "DecalPool", "class_impact_c_f_x_1_1_decals_1_1_decal_pool.html", null ],
        [ "ImpactDecal", "class_impact_c_f_x_1_1_decals_1_1_impact_decal.html", "class_impact_c_f_x_1_1_decals_1_1_impact_decal" ],
        [ "ImpactDecalBase", "class_impact_c_f_x_1_1_decals_1_1_impact_decal_base.html", "class_impact_c_f_x_1_1_decals_1_1_impact_decal_base" ],
        [ "ImpactDecalEffectAuthoring", "class_impact_c_f_x_1_1_decals_1_1_impact_decal_effect_authoring.html", null ],
        [ "ImpactDecalEffectProcessor", "class_impact_c_f_x_1_1_decals_1_1_impact_decal_effect_processor.html", null ]
      ] ],
      [ "Particles", "namespace_impact_c_f_x_1_1_particles.html", [
        [ "ImpactParticleEffectAuthoring", "class_impact_c_f_x_1_1_particles_1_1_impact_particle_effect_authoring.html", null ],
        [ "ImpactParticleEffectProcessor", "class_impact_c_f_x_1_1_particles_1_1_impact_particle_effect_processor.html", null ],
        [ "ImpactParticlesBase", "class_impact_c_f_x_1_1_particles_1_1_impact_particles_base.html", "class_impact_c_f_x_1_1_particles_1_1_impact_particles_base" ],
        [ "ImpactParticleSystem", "class_impact_c_f_x_1_1_particles_1_1_impact_particle_system.html", "class_impact_c_f_x_1_1_particles_1_1_impact_particle_system" ],
        [ "ParticleEffect", "struct_impact_c_f_x_1_1_particles_1_1_particle_effect.html", "struct_impact_c_f_x_1_1_particles_1_1_particle_effect" ],
        [ "ParticleEffectResult", "struct_impact_c_f_x_1_1_particles_1_1_particle_effect_result.html", "struct_impact_c_f_x_1_1_particles_1_1_particle_effect_result" ],
        [ "ParticlePool", "class_impact_c_f_x_1_1_particles_1_1_particle_pool.html", null ]
      ] ],
      [ "Pooling", "namespace_impact_c_f_x_1_1_pooling.html", [
        [ "IObjectPoolRequest", "interface_impact_c_f_x_1_1_pooling_1_1_i_object_pool_request.html", "interface_impact_c_f_x_1_1_pooling_1_1_i_object_pool_request" ],
        [ "IPoolable", "interface_impact_c_f_x_1_1_pooling_1_1_i_poolable.html", "interface_impact_c_f_x_1_1_pooling_1_1_i_poolable" ],
        [ "ObjectPool< T >", "class_impact_c_f_x_1_1_pooling_1_1_object_pool-1-g.html", "class_impact_c_f_x_1_1_pooling_1_1_object_pool-1-g" ],
        [ "ObjectPoolConfig", "class_impact_c_f_x_1_1_pooling_1_1_object_pool_config.html", "class_impact_c_f_x_1_1_pooling_1_1_object_pool_config" ],
        [ "ObjectPoolJob< TRequest >", "struct_impact_c_f_x_1_1_pooling_1_1_object_pool_job-1-g.html", "struct_impact_c_f_x_1_1_pooling_1_1_object_pool_job-1-g" ],
        [ "PooledObjectData", "struct_impact_c_f_x_1_1_pooling_1_1_pooled_object_data.html", "struct_impact_c_f_x_1_1_pooling_1_1_pooled_object_data" ]
      ] ],
      [ "Triggers", "namespace_impact_c_f_x_1_1_triggers.html", [
        [ "ImpactCollisionTrigger2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_collision_trigger2_d.html", null ],
        [ "ImpactCollisionTrigger3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_collision_trigger3_d.html", null ],
        [ "ImpactCollisionTriggerBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_collision_trigger_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_collision_trigger_base" ],
        [ "ImpactOnTriggerEnter2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_enter2_d.html", null ],
        [ "ImpactOnTriggerEnter3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_enter3_d.html", null ],
        [ "ImpactOnTriggerEnterBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_enter_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_enter_base" ],
        [ "ImpactOnTriggerStay2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_stay2_d.html", null ],
        [ "ImpactOnTriggerStay3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_stay3_d.html", null ],
        [ "ImpactOnTriggerStayBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_stay_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_on_trigger_stay_base" ],
        [ "ImpactParticleSystemCollisionTrigger", "class_impact_c_f_x_1_1_triggers_1_1_impact_particle_system_collision_trigger.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_particle_system_collision_trigger" ],
        [ "ImpactSimpleCollisionTrigger2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_simple_collision_trigger2_d.html", null ],
        [ "ImpactSimpleCollisionTrigger3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_simple_collision_trigger3_d.html", null ],
        [ "ImpactSimpleCollisionTriggerBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_simple_collision_trigger_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_simple_collision_trigger_base" ],
        [ "ImpactSlideAndRollTrigger2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_slide_and_roll_trigger2_d.html", null ],
        [ "ImpactSlideAndRollTrigger3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_slide_and_roll_trigger3_d.html", null ],
        [ "ImpactSlideAndRollTriggerBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_slide_and_roll_trigger_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_slide_and_roll_trigger_base" ],
        [ "ImpactSpeculativeCollisionTrigger2D", "class_impact_c_f_x_1_1_triggers_1_1_impact_speculative_collision_trigger2_d.html", null ],
        [ "ImpactSpeculativeCollisionTrigger3D", "class_impact_c_f_x_1_1_triggers_1_1_impact_speculative_collision_trigger3_d.html", null ],
        [ "ImpactSpeculativeCollisionTriggerBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_speculative_collision_trigger_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_speculative_collision_trigger_base" ],
        [ "ImpactTriggerBase", "class_impact_c_f_x_1_1_triggers_1_1_impact_trigger_base.html", "class_impact_c_f_x_1_1_triggers_1_1_impact_trigger_base" ]
      ] ],
      [ "AlignmentAxisUtilities", "class_impact_c_f_x_1_1_alignment_axis_utilities.html", "class_impact_c_f_x_1_1_alignment_axis_utilities" ],
      [ "ArrayChunk", "struct_impact_c_f_x_1_1_array_chunk.html", "struct_impact_c_f_x_1_1_array_chunk" ],
      [ "Bitmask", "class_impact_c_f_x_1_1_bitmask.html", "class_impact_c_f_x_1_1_bitmask" ],
      [ "CollisionInputData", "struct_impact_c_f_x_1_1_collision_input_data.html", "struct_impact_c_f_x_1_1_collision_input_data" ],
      [ "CollisionObjectPair", "struct_impact_c_f_x_1_1_collision_object_pair.html", "struct_impact_c_f_x_1_1_collision_object_pair" ],
      [ "CollisionResultData", "struct_impact_c_f_x_1_1_collision_result_data.html", "struct_impact_c_f_x_1_1_collision_result_data" ],
      [ "CollisionTypeExtensions", "class_impact_c_f_x_1_1_collision_type_extensions.html", "class_impact_c_f_x_1_1_collision_type_extensions" ],
      [ "ContactPointIDGenerator", "class_impact_c_f_x_1_1_contact_point_i_d_generator.html", "class_impact_c_f_x_1_1_contact_point_i_d_generator" ],
      [ "EffectObjectPool< T >", "class_impact_c_f_x_1_1_effect_object_pool-1-g.html", "class_impact_c_f_x_1_1_effect_object_pool-1-g" ],
      [ "EffectUtility", "class_impact_c_f_x_1_1_effect_utility.html", "class_impact_c_f_x_1_1_effect_utility" ],
      [ "EffectVelocityModifier", "class_impact_c_f_x_1_1_effect_velocity_modifier.html", "class_impact_c_f_x_1_1_effect_velocity_modifier" ],
      [ "GameObjectExtensions", "class_impact_c_f_x_1_1_game_object_extensions.html", "class_impact_c_f_x_1_1_game_object_extensions" ],
      [ "IEffectData< TResult >", "interface_impact_c_f_x_1_1_i_effect_data-1-g.html", "interface_impact_c_f_x_1_1_i_effect_data-1-g" ],
      [ "IEffectResult", "interface_impact_c_f_x_1_1_i_effect_result.html", "interface_impact_c_f_x_1_1_i_effect_result" ],
      [ "IImpactObject", "interface_impact_c_f_x_1_1_i_impact_object.html", "interface_impact_c_f_x_1_1_i_impact_object" ],
      [ "ImpactAttachedEffectManager", "class_impact_c_f_x_1_1_impact_attached_effect_manager.html", "class_impact_c_f_x_1_1_impact_attached_effect_manager" ],
      [ "ImpactCFXGlobal", "class_impact_c_f_x_1_1_impact_c_f_x_global.html", "class_impact_c_f_x_1_1_impact_c_f_x_global" ],
      [ "ImpactCFXLogger", "class_impact_c_f_x_1_1_impact_c_f_x_logger.html", "class_impact_c_f_x_1_1_impact_c_f_x_logger" ],
      [ "ImpactCFXManager", "class_impact_c_f_x_1_1_impact_c_f_x_manager.html", "class_impact_c_f_x_1_1_impact_c_f_x_manager" ],
      [ "ImpactCollision", "struct_impact_c_f_x_1_1_impact_collision.html", "struct_impact_c_f_x_1_1_impact_collision" ],
      [ "ImpactContactPoint", "struct_impact_c_f_x_1_1_impact_contact_point.html", "struct_impact_c_f_x_1_1_impact_contact_point" ],
      [ "ImpactEffectAuthoringBase", "class_impact_c_f_x_1_1_impact_effect_authoring_base.html", "class_impact_c_f_x_1_1_impact_effect_authoring_base" ],
      [ "ImpactEffectProcessorBase", "class_impact_c_f_x_1_1_impact_effect_processor_base.html", "class_impact_c_f_x_1_1_impact_effect_processor_base" ],
      [ "ImpactEffectProcessorJob< TEffect, TResult >", "struct_impact_c_f_x_1_1_impact_effect_processor_job-2-g.html", "struct_impact_c_f_x_1_1_impact_effect_processor_job-2-g" ],
      [ "ImpactMaterialAuthoring", "class_impact_c_f_x_1_1_impact_material_authoring.html", "class_impact_c_f_x_1_1_impact_material_authoring" ],
      [ "ImpactMaterialData", "struct_impact_c_f_x_1_1_impact_material_data.html", "struct_impact_c_f_x_1_1_impact_material_data" ],
      [ "ImpactMaterialDataResetJob", "struct_impact_c_f_x_1_1_impact_material_data_reset_job.html", null ],
      [ "ImpactMaterialMappingProcessor", "class_impact_c_f_x_1_1_impact_material_mapping_processor.html", null ],
      [ "ImpactMaterialProcessorBase", "class_impact_c_f_x_1_1_impact_material_processor_base.html", "class_impact_c_f_x_1_1_impact_material_processor_base" ],
      [ "ImpactMaterialRegistry", "class_impact_c_f_x_1_1_impact_material_registry.html", null ],
      [ "ImpactMultiPrefabEffectAuthoringBase", "class_impact_c_f_x_1_1_impact_multi_prefab_effect_authoring_base.html", "class_impact_c_f_x_1_1_impact_multi_prefab_effect_authoring_base" ],
      [ "ImpactMultiPrefabEffectProcessor< TEffectAuthoring, TEffect, TEffectResult, TPool, TPooledObject >", "class_impact_c_f_x_1_1_impact_multi_prefab_effect_processor-5-g.html", "class_impact_c_f_x_1_1_impact_multi_prefab_effect_processor-5-g" ],
      [ "ImpactMultiPrefabJob< TResult >", "struct_impact_c_f_x_1_1_impact_multi_prefab_job-1-g.html", "struct_impact_c_f_x_1_1_impact_multi_prefab_job-1-g" ],
      [ "ImpactObjectBase", "class_impact_c_f_x_1_1_impact_object_base.html", "class_impact_c_f_x_1_1_impact_object_base" ],
      [ "ImpactObjectChild", "class_impact_c_f_x_1_1_impact_object_child.html", "class_impact_c_f_x_1_1_impact_object_child" ],
      [ "ImpactObjectCustomVelocity", "class_impact_c_f_x_1_1_impact_object_custom_velocity.html", "class_impact_c_f_x_1_1_impact_object_custom_velocity" ],
      [ "ImpactObjectData", "struct_impact_c_f_x_1_1_impact_object_data.html", "struct_impact_c_f_x_1_1_impact_object_data" ],
      [ "ImpactObjectRigidbody", "class_impact_c_f_x_1_1_impact_object_rigidbody.html", "class_impact_c_f_x_1_1_impact_object_rigidbody" ],
      [ "ImpactObjectRigidbodyCheap", "class_impact_c_f_x_1_1_impact_object_rigidbody_cheap.html", "class_impact_c_f_x_1_1_impact_object_rigidbody_cheap" ],
      [ "ImpactObjectSingleMaterial", "class_impact_c_f_x_1_1_impact_object_single_material.html", "class_impact_c_f_x_1_1_impact_object_single_material" ],
      [ "ImpactObjectTerrain", "class_impact_c_f_x_1_1_impact_object_terrain.html", "class_impact_c_f_x_1_1_impact_object_terrain" ],
      [ "ImpactPhysicMaterialMapping", "class_impact_c_f_x_1_1_impact_physic_material_mapping.html", "class_impact_c_f_x_1_1_impact_physic_material_mapping" ],
      [ "ImpactPhysicsMaterial2DMapping", "class_impact_c_f_x_1_1_impact_physics_material2_d_mapping.html", "class_impact_c_f_x_1_1_impact_physics_material2_d_mapping" ],
      [ "ImpactPooledEffectAuthoringBase", "class_impact_c_f_x_1_1_impact_pooled_effect_authoring_base.html", "class_impact_c_f_x_1_1_impact_pooled_effect_authoring_base" ],
      [ "ImpactPooledEffectProcessor< TEffectAuthoring, TEffect, TEffectResult, TPool, TPooledObject >", "class_impact_c_f_x_1_1_impact_pooled_effect_processor-5-g.html", "class_impact_c_f_x_1_1_impact_pooled_effect_processor-5-g" ],
      [ "ImpactRaycaster", "class_impact_c_f_x_1_1_impact_raycaster.html", "class_impact_c_f_x_1_1_impact_raycaster" ],
      [ "ImpactSimpleEffectProcessor< TEffectAuthoring, TEffect, TEffectResult >", "class_impact_c_f_x_1_1_impact_simple_effect_processor-3-g.html", "class_impact_c_f_x_1_1_impact_simple_effect_processor-3-g" ],
      [ "ImpactSingleMaterialProcessor", "class_impact_c_f_x_1_1_impact_single_material_processor.html", null ],
      [ "ImpactTag", "struct_impact_c_f_x_1_1_impact_tag.html", "struct_impact_c_f_x_1_1_impact_tag" ],
      [ "ImpactTagMask", "struct_impact_c_f_x_1_1_impact_tag_mask.html", "struct_impact_c_f_x_1_1_impact_tag_mask" ],
      [ "ImpactTagMaskFilter", "struct_impact_c_f_x_1_1_impact_tag_mask_filter.html", "struct_impact_c_f_x_1_1_impact_tag_mask_filter" ],
      [ "ImpactTerrainMaterialProcessor", "class_impact_c_f_x_1_1_impact_terrain_material_processor.html", null ],
      [ "ImpactVelocityData", "struct_impact_c_f_x_1_1_impact_velocity_data.html", "struct_impact_c_f_x_1_1_impact_velocity_data" ],
      [ "ImpactVelocityDataJob", "struct_impact_c_f_x_1_1_impact_velocity_data_job.html", null ],
      [ "IMultiPrefabEffectData< TResult >", "interface_impact_c_f_x_1_1_i_multi_prefab_effect_data-1-g.html", "interface_impact_c_f_x_1_1_i_multi_prefab_effect_data-1-g" ],
      [ "IMultiPrefabEffectResult", "interface_impact_c_f_x_1_1_i_multi_prefab_effect_result.html", "interface_impact_c_f_x_1_1_i_multi_prefab_effect_result" ],
      [ "IPooledEffectData< TResult >", "interface_impact_c_f_x_1_1_i_pooled_effect_data-1-g.html", "interface_impact_c_f_x_1_1_i_pooled_effect_data-1-g" ],
      [ "MaterialCompositionData", "struct_impact_c_f_x_1_1_material_composition_data.html", "struct_impact_c_f_x_1_1_material_composition_data" ],
      [ "ObjectID", "struct_impact_c_f_x_1_1_object_i_d.html", "struct_impact_c_f_x_1_1_object_i_d" ],
      [ "ObjectIDExtensions", "class_impact_c_f_x_1_1_object_i_d_extensions.html", "class_impact_c_f_x_1_1_object_i_d_extensions" ],
      [ "OverrideValue< T >", "class_impact_c_f_x_1_1_override_value-1-g.html", null ],
      [ "OverrideValueInt", "class_impact_c_f_x_1_1_override_value_int.html", null ],
      [ "PhysicsUtility", "class_impact_c_f_x_1_1_physics_utility.html", "class_impact_c_f_x_1_1_physics_utility" ],
      [ "PooledEffectObjectBase", "class_impact_c_f_x_1_1_pooled_effect_object_base.html", "class_impact_c_f_x_1_1_pooled_effect_object_base" ],
      [ "Range", "struct_impact_c_f_x_1_1_range.html", "struct_impact_c_f_x_1_1_range" ],
      [ "RigidbodyContainer", "class_impact_c_f_x_1_1_rigidbody_container.html", "class_impact_c_f_x_1_1_rigidbody_container" ],
      [ "RigidbodyData", "struct_impact_c_f_x_1_1_rigidbody_data.html", "struct_impact_c_f_x_1_1_rigidbody_data" ],
      [ "RigidbodyStateData", "struct_impact_c_f_x_1_1_rigidbody_state_data.html", "struct_impact_c_f_x_1_1_rigidbody_state_data" ],
      [ "TransformData", "struct_impact_c_f_x_1_1_transform_data.html", "struct_impact_c_f_x_1_1_transform_data" ]
    ] ]
];