var namespace_impact_c_f_x =
[
    [ "Audio", "namespace_impact_c_f_x_1_1_audio.html", "namespace_impact_c_f_x_1_1_audio" ],
    [ "Decals", "namespace_impact_c_f_x_1_1_decals.html", "namespace_impact_c_f_x_1_1_decals" ],
    [ "Particles", "namespace_impact_c_f_x_1_1_particles.html", "namespace_impact_c_f_x_1_1_particles" ],
    [ "Pooling", "namespace_impact_c_f_x_1_1_pooling.html", "namespace_impact_c_f_x_1_1_pooling" ],
    [ "AlignmentAxisUtilities", "class_impact_c_f_x_1_1_alignment_axis_utilities.html", "class_impact_c_f_x_1_1_alignment_axis_utilities" ],
    [ "ArrayChunk", "struct_impact_c_f_x_1_1_array_chunk.html", "struct_impact_c_f_x_1_1_array_chunk" ],
    [ "Bitmask", "class_impact_c_f_x_1_1_bitmask.html", "class_impact_c_f_x_1_1_bitmask" ],
    [ "CollisionInputData", "struct_impact_c_f_x_1_1_collision_input_data.html", "struct_impact_c_f_x_1_1_collision_input_data" ],
    [ "CollisionObjectPair", "struct_impact_c_f_x_1_1_collision_object_pair.html", "struct_impact_c_f_x_1_1_collision_object_pair" ],
    [ "CollisionResultData", "struct_impact_c_f_x_1_1_collision_result_data.html", "struct_impact_c_f_x_1_1_collision_result_data" ],
    [ "CollisionTypeExtensions", "class_impact_c_f_x_1_1_collision_type_extensions.html", "class_impact_c_f_x_1_1_collision_type_extensions" ],
    [ "CollisionTypeLimit", "class_impact_c_f_x_1_1_collision_type_limit.html", null ],
    [ "ContactPointIDGenerator", "class_impact_c_f_x_1_1_contact_point_i_d_generator.html", "class_impact_c_f_x_1_1_contact_point_i_d_generator" ],
    [ "EffectUtility", "class_impact_c_f_x_1_1_effect_utility.html", "class_impact_c_f_x_1_1_effect_utility" ],
    [ "GameObjectExtensions", "class_impact_c_f_x_1_1_game_object_extensions.html", "class_impact_c_f_x_1_1_game_object_extensions" ],
    [ "IEffectData", "interface_impact_c_f_x_1_1_i_effect_data.html", "interface_impact_c_f_x_1_1_i_effect_data" ],
    [ "IEffectResult", "interface_impact_c_f_x_1_1_i_effect_result.html", "interface_impact_c_f_x_1_1_i_effect_result" ],
    [ "IImpactObject", "interface_impact_c_f_x_1_1_i_impact_object.html", "interface_impact_c_f_x_1_1_i_impact_object" ],
    [ "ImpactAttachedEffectManager", "class_impact_c_f_x_1_1_impact_attached_effect_manager.html", "class_impact_c_f_x_1_1_impact_attached_effect_manager" ],
    [ "ImpactCFXGlobal", "class_impact_c_f_x_1_1_impact_c_f_x_global.html", "class_impact_c_f_x_1_1_impact_c_f_x_global" ],
    [ "ImpactCFXLogger", "class_impact_c_f_x_1_1_impact_c_f_x_logger.html", null ],
    [ "ImpactCFXManager", "class_impact_c_f_x_1_1_impact_c_f_x_manager.html", "class_impact_c_f_x_1_1_impact_c_f_x_manager" ],
    [ "ImpactCollision", "struct_impact_c_f_x_1_1_impact_collision.html", "struct_impact_c_f_x_1_1_impact_collision" ],
    [ "ImpactCollisionTrigger2D", "class_impact_c_f_x_1_1_impact_collision_trigger2_d.html", null ],
    [ "ImpactCollisionTrigger3D", "class_impact_c_f_x_1_1_impact_collision_trigger3_d.html", null ],
    [ "ImpactCollisionTriggerBase", "class_impact_c_f_x_1_1_impact_collision_trigger_base.html", "class_impact_c_f_x_1_1_impact_collision_trigger_base" ],
    [ "ImpactContactPoint", "struct_impact_c_f_x_1_1_impact_contact_point.html", "struct_impact_c_f_x_1_1_impact_contact_point" ],
    [ "ImpactDistancePriorityJob", "struct_impact_c_f_x_1_1_impact_distance_priority_job.html", null ],
    [ "ImpactEffectAuthoringBase", "class_impact_c_f_x_1_1_impact_effect_authoring_base.html", "class_impact_c_f_x_1_1_impact_effect_authoring_base" ],
    [ "ImpactEffectProcessorBase", "class_impact_c_f_x_1_1_impact_effect_processor_base.html", "class_impact_c_f_x_1_1_impact_effect_processor_base" ],
    [ "ImpactEffectProcessorJob", "struct_impact_c_f_x_1_1_impact_effect_processor_job.html", "struct_impact_c_f_x_1_1_impact_effect_processor_job" ],
    [ "ImpactMaterialAuthoring", "class_impact_c_f_x_1_1_impact_material_authoring.html", null ],
    [ "ImpactMaterialAuthoringEffectSet", "class_impact_c_f_x_1_1_impact_material_authoring_effect_set.html", null ],
    [ "ImpactMaterialData", "struct_impact_c_f_x_1_1_impact_material_data.html", "struct_impact_c_f_x_1_1_impact_material_data" ],
    [ "ImpactMaterialDataResetJob", "struct_impact_c_f_x_1_1_impact_material_data_reset_job.html", null ],
    [ "ImpactMaterialMappingJob", "struct_impact_c_f_x_1_1_impact_material_mapping_job.html", null ],
    [ "ImpactMaterialMappingJobParameter", "struct_impact_c_f_x_1_1_impact_material_mapping_job_parameter.html", null ],
    [ "ImpactMaterialMappingProcessor", "class_impact_c_f_x_1_1_impact_material_mapping_processor.html", null ],
    [ "ImpactMaterialProcessorBase", "class_impact_c_f_x_1_1_impact_material_processor_base.html", "class_impact_c_f_x_1_1_impact_material_processor_base" ],
    [ "ImpactMaterialRegistry", "class_impact_c_f_x_1_1_impact_material_registry.html", null ],
    [ "ImpactObjectBase", "class_impact_c_f_x_1_1_impact_object_base.html", "class_impact_c_f_x_1_1_impact_object_base" ],
    [ "ImpactObjectData", "struct_impact_c_f_x_1_1_impact_object_data.html", "struct_impact_c_f_x_1_1_impact_object_data" ],
    [ "ImpactObjectRigidbody", "class_impact_c_f_x_1_1_impact_object_rigidbody.html", "class_impact_c_f_x_1_1_impact_object_rigidbody" ],
    [ "ImpactObjectRigidbodyChild", "class_impact_c_f_x_1_1_impact_object_rigidbody_child.html", "class_impact_c_f_x_1_1_impact_object_rigidbody_child" ],
    [ "ImpactObjectSingleMaterial", "class_impact_c_f_x_1_1_impact_object_single_material.html", "class_impact_c_f_x_1_1_impact_object_single_material" ],
    [ "ImpactObjectTerrain", "class_impact_c_f_x_1_1_impact_object_terrain.html", "class_impact_c_f_x_1_1_impact_object_terrain" ],
    [ "ImpactOnTriggerEnter2D", "class_impact_c_f_x_1_1_impact_on_trigger_enter2_d.html", null ],
    [ "ImpactOnTriggerEnter3D", "class_impact_c_f_x_1_1_impact_on_trigger_enter3_d.html", null ],
    [ "ImpactOnTriggerEnterBase", "class_impact_c_f_x_1_1_impact_on_trigger_enter_base.html", "class_impact_c_f_x_1_1_impact_on_trigger_enter_base" ],
    [ "ImpactOnTriggerStay2D", "class_impact_c_f_x_1_1_impact_on_trigger_stay2_d.html", null ],
    [ "ImpactOnTriggerStay3D", "class_impact_c_f_x_1_1_impact_on_trigger_stay3_d.html", null ],
    [ "ImpactOnTriggerStayBase", "class_impact_c_f_x_1_1_impact_on_trigger_stay_base.html", "class_impact_c_f_x_1_1_impact_on_trigger_stay_base" ],
    [ "ImpactParticleSystemCollisionTrigger", "class_impact_c_f_x_1_1_impact_particle_system_collision_trigger.html", "class_impact_c_f_x_1_1_impact_particle_system_collision_trigger" ],
    [ "ImpactPhysicMaterialMapping", "class_impact_c_f_x_1_1_impact_physic_material_mapping.html", "class_impact_c_f_x_1_1_impact_physic_material_mapping" ],
    [ "ImpactPhysicsMaterial2DMapping", "class_impact_c_f_x_1_1_impact_physics_material2_d_mapping.html", "class_impact_c_f_x_1_1_impact_physics_material2_d_mapping" ],
    [ "ImpactRaycaster", "class_impact_c_f_x_1_1_impact_raycaster.html", "class_impact_c_f_x_1_1_impact_raycaster" ],
    [ "ImpactSimpleCollisionTrigger2D", "class_impact_c_f_x_1_1_impact_simple_collision_trigger2_d.html", null ],
    [ "ImpactSimpleCollisionTrigger3D", "class_impact_c_f_x_1_1_impact_simple_collision_trigger3_d.html", null ],
    [ "ImpactSimpleCollisionTriggerBase", "class_impact_c_f_x_1_1_impact_simple_collision_trigger_base.html", "class_impact_c_f_x_1_1_impact_simple_collision_trigger_base" ],
    [ "ImpactSingleMaterialJob", "struct_impact_c_f_x_1_1_impact_single_material_job.html", null ],
    [ "ImpactSingleMaterialJobParameter", "struct_impact_c_f_x_1_1_impact_single_material_job_parameter.html", null ],
    [ "ImpactSingleMaterialProcessor", "class_impact_c_f_x_1_1_impact_single_material_processor.html", "class_impact_c_f_x_1_1_impact_single_material_processor" ],
    [ "ImpactSlideAndRollTrigger2D", "class_impact_c_f_x_1_1_impact_slide_and_roll_trigger2_d.html", null ],
    [ "ImpactSlideAndRollTrigger3D", "class_impact_c_f_x_1_1_impact_slide_and_roll_trigger3_d.html", null ],
    [ "ImpactSlideAndRollTriggerBase", "class_impact_c_f_x_1_1_impact_slide_and_roll_trigger_base.html", "class_impact_c_f_x_1_1_impact_slide_and_roll_trigger_base" ],
    [ "ImpactSpeculativeCollisionTrigger2D", "class_impact_c_f_x_1_1_impact_speculative_collision_trigger2_d.html", null ],
    [ "ImpactSpeculativeCollisionTrigger3D", "class_impact_c_f_x_1_1_impact_speculative_collision_trigger3_d.html", null ],
    [ "ImpactSpeculativeCollisionTriggerBase", "class_impact_c_f_x_1_1_impact_speculative_collision_trigger_base.html", "class_impact_c_f_x_1_1_impact_speculative_collision_trigger_base" ],
    [ "ImpactTag", "struct_impact_c_f_x_1_1_impact_tag.html", "struct_impact_c_f_x_1_1_impact_tag" ],
    [ "ImpactTagMask", "struct_impact_c_f_x_1_1_impact_tag_mask.html", "struct_impact_c_f_x_1_1_impact_tag_mask" ],
    [ "ImpactTagMaskFilter", "struct_impact_c_f_x_1_1_impact_tag_mask_filter.html", "struct_impact_c_f_x_1_1_impact_tag_mask_filter" ],
    [ "ImpactTerrainMaterialJob", "struct_impact_c_f_x_1_1_impact_terrain_material_job.html", null ],
    [ "ImpactTerrainMaterialJobParameter", "struct_impact_c_f_x_1_1_impact_terrain_material_job_parameter.html", null ],
    [ "ImpactTerrainMaterialProcessor", "class_impact_c_f_x_1_1_impact_terrain_material_processor.html", "class_impact_c_f_x_1_1_impact_terrain_material_processor" ],
    [ "ImpactTriggerBase", "class_impact_c_f_x_1_1_impact_trigger_base.html", "class_impact_c_f_x_1_1_impact_trigger_base" ],
    [ "ImpactVelocityData", "struct_impact_c_f_x_1_1_impact_velocity_data.html", "struct_impact_c_f_x_1_1_impact_velocity_data" ],
    [ "ImpactVelocityDataJob", "struct_impact_c_f_x_1_1_impact_velocity_data_job.html", null ],
    [ "MaterialCompositionData", "struct_impact_c_f_x_1_1_material_composition_data.html", "struct_impact_c_f_x_1_1_material_composition_data" ],
    [ "OverrideValue", "class_impact_c_f_x_1_1_override_value.html", null ],
    [ "OverrideValueInt", "class_impact_c_f_x_1_1_override_value_int.html", null ],
    [ "PhysicsUtility", "class_impact_c_f_x_1_1_physics_utility.html", "class_impact_c_f_x_1_1_physics_utility" ],
    [ "PooledEffectObjectBase", "class_impact_c_f_x_1_1_pooled_effect_object_base.html", "class_impact_c_f_x_1_1_pooled_effect_object_base" ],
    [ "Range", "struct_impact_c_f_x_1_1_range.html", "struct_impact_c_f_x_1_1_range" ],
    [ "RigidbodyData", "struct_impact_c_f_x_1_1_rigidbody_data.html", "struct_impact_c_f_x_1_1_rigidbody_data" ],
    [ "RigidbodyStateData", "struct_impact_c_f_x_1_1_rigidbody_state_data.html", "struct_impact_c_f_x_1_1_rigidbody_state_data" ],
    [ "TransformData", "struct_impact_c_f_x_1_1_transform_data.html", "struct_impact_c_f_x_1_1_transform_data" ],
    [ "AlignmentAxis", "namespace_impact_c_f_x.html#ad60fa27de967f3abed662e4664a68df5", [
      [ "ZDown", "namespace_impact_c_f_x.html#ad60fa27de967f3abed662e4664a68df5a97a2284847de79b1515608bd2d2e0d8c", null ],
      [ "ZUp", "namespace_impact_c_f_x.html#ad60fa27de967f3abed662e4664a68df5a45ce487e12a916f5e631b665663e8d45", null ],
      [ "YDown", "namespace_impact_c_f_x.html#ad60fa27de967f3abed662e4664a68df5aaa110f0660ac26c6d4c1916d5c15ebf2", null ],
      [ "YUp", "namespace_impact_c_f_x.html#ad60fa27de967f3abed662e4664a68df5a9ae296447960cdeff675af5d3b0b41c9", null ]
    ] ],
    [ "CollisionNormalMode", "namespace_impact_c_f_x.html#a076503f918b514c229fb4fbd8d2e32d6", [
      [ "Default", "namespace_impact_c_f_x.html#a076503f918b514c229fb4fbd8d2e32d6a7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Inverted", "namespace_impact_c_f_x.html#a076503f918b514c229fb4fbd8d2e32d6acf4c2a4bf7c328c4e51f902350475343", null ]
    ] ],
    [ "CollisionType", "namespace_impact_c_f_x.html#ab1d919ce67cfec1a7c1139d28d9c9596", [
      [ "Collision", "namespace_impact_c_f_x.html#ab1d919ce67cfec1a7c1139d28d9c9596a15fb6ccbd11ebebcea2b48dc477f3561", null ],
      [ "Slide", "namespace_impact_c_f_x.html#ab1d919ce67cfec1a7c1139d28d9c9596a6160a53ece50ce6d4f5ef4452549835e", null ],
      [ "Roll", "namespace_impact_c_f_x.html#ab1d919ce67cfec1a7c1139d28d9c9596a25b5eb3bbef15385b5f5ff3abe46f342", null ]
    ] ],
    [ "EffectAttachMode", "namespace_impact_c_f_x.html#a71e2cb9f00fc8c29e4843f9c91c4a5fd", [
      [ "None", "namespace_impact_c_f_x.html#a71e2cb9f00fc8c29e4843f9c91c4a5fda6adf97f83acf6453d4a6a4b1070f3754", null ],
      [ "TriggerObject", "namespace_impact_c_f_x.html#a71e2cb9f00fc8c29e4843f9c91c4a5fdae59684927b821041c2cbf32a1ef1218b", null ],
      [ "HitObject", "namespace_impact_c_f_x.html#a71e2cb9f00fc8c29e4843f9c91c4a5fda5e73d7babacace42682a9ceea1a3e8fb", null ]
    ] ],
    [ "EffectIntervalType", "namespace_impact_c_f_x.html#a4ba86e1b99a69a401cc72377f5d41d92", [
      [ "Time", "namespace_impact_c_f_x.html#a4ba86e1b99a69a401cc72377f5d41d92aa76d4ef5f3f6a672bbfab2865563e530", null ],
      [ "Distance", "namespace_impact_c_f_x.html#a4ba86e1b99a69a401cc72377f5d41d92a0aa6f4210bf373c95eda00232e93cd98", null ]
    ] ],
    [ "ImpactTriggerContactMode", "namespace_impact_c_f_x.html#abac7ace401e0571ced5c322b08656c45", [
      [ "Single", "namespace_impact_c_f_x.html#abac7ace401e0571ced5c322b08656c45a66ba162102bbf6ae31b522aec561735e", null ],
      [ "Average", "namespace_impact_c_f_x.html#abac7ace401e0571ced5c322b08656c45ab1897515d548a960afe49ecf66a29021", null ]
    ] ],
    [ "ParticleEffectType", "namespace_impact_c_f_x.html#a353dd063fd020f13681cb010e0455554", [
      [ "OneShot", "namespace_impact_c_f_x.html#a353dd063fd020f13681cb010e0455554ac7fc2ee61fad0e2bba6754efdee31481", null ],
      [ "Looped", "namespace_impact_c_f_x.html#a353dd063fd020f13681cb010e0455554aea3b2042a17eee4c899f43a304a09432", null ]
    ] ],
    [ "PhysicsType", "namespace_impact_c_f_x.html#affe2215e14c3558a4a58114cf076a6ff", [
      [ "Unknown", "namespace_impact_c_f_x.html#affe2215e14c3558a4a58114cf076a6ffa88183b946cc5f0e8c96b2e66e1c74a7e", null ],
      [ "Physics3D", "namespace_impact_c_f_x.html#affe2215e14c3558a4a58114cf076a6ffabbc2dc2a3d7e88ea17dde0a2951d2cdc", null ],
      [ "Physics2D", "namespace_impact_c_f_x.html#affe2215e14c3558a4a58114cf076a6ffaf0151601ed0b8ef1f708f94fa5c9208c", null ]
    ] ]
];