var searchData=
[
  ['audio_0',['Audio',['../namespace_impact_1_1_interactions_1_1_audio.html',1,'Impact::Interactions']]],
  ['data_1',['Data',['../namespace_impact_1_1_data.html',1,'Impact']]],
  ['decals_2',['Decals',['../namespace_impact_1_1_interactions_1_1_decals.html',1,'Impact::Interactions']]],
  ['icontinuousinteractionresult_3',['IContinuousInteractionResult',['../interface_impact_1_1_interactions_1_1_i_continuous_interaction_result.html',1,'Impact::Interactions']]],
  ['iimpactcollisionwrapper_4',['IImpactCollisionWrapper',['../interface_impact_1_1_i_impact_collision_wrapper.html',1,'Impact']]],
  ['iimpactcollisionwrapper_3c_20impactcontactpoint_20_3e_5',['IImpactCollisionWrapper&lt; ImpactContactPoint &gt;',['../interface_impact_1_1_i_impact_collision_wrapper.html',1,'Impact']]],
  ['iimpactcontactpoint_6',['IImpactContactPoint',['../interface_impact_1_1_i_impact_contact_point.html',1,'Impact']]],
  ['iimpactinteraction_7',['IImpactInteraction',['../interface_impact_1_1_interactions_1_1_i_impact_interaction.html',1,'Impact::Interactions']]],
  ['iimpactmaterial_8',['IImpactMaterial',['../interface_impact_1_1_materials_1_1_i_impact_material.html',1,'Impact::Materials']]],
  ['iimpactobject_9',['IImpactObject',['../interface_impact_1_1_objects_1_1_i_impact_object.html',1,'Impact::Objects']]],
  ['iimpacttaglibrary_10',['IImpactTagLibrary',['../interface_impact_1_1_tag_library_1_1_i_impact_tag_library.html',1,'Impact::TagLibrary']]],
  ['iimpacttrigger_11',['IImpactTrigger',['../interface_impact_1_1_triggers_1_1_i_impact_trigger.html',1,'Impact::Triggers']]],
  ['iinteractiondata_12',['IInteractionData',['../interface_impact_1_1_i_interaction_data.html',1,'Impact']]],
  ['iinteractionresult_13',['IInteractionResult',['../interface_impact_1_1_interactions_1_1_i_interaction_result.html',1,'Impact::Interactions']]],
  ['impact_14',['Impact',['../namespace_impact.html',1,'']]],
  ['impactaotworkaround_15',['ImpactAOTWorkaround',['../class_impact_1_1_impact_a_o_t_workaround.html',1,'Impact']]],
  ['impactaudiointeraction_16',['ImpactAudioInteraction',['../class_impact_1_1_interactions_1_1_audio_1_1_impact_audio_interaction.html',1,'Impact::Interactions::Audio']]],
  ['impactaudiopool_17',['ImpactAudioPool',['../class_impact_1_1_interactions_1_1_audio_1_1_impact_audio_pool.html',1,'Impact::Interactions::Audio']]],
  ['impactaudiosource_18',['ImpactAudioSource',['../class_impact_1_1_interactions_1_1_audio_1_1_impact_audio_source.html',1,'Impact::Interactions::Audio']]],
  ['impactaudiosourcebase_19',['ImpactAudioSourceBase',['../class_impact_1_1_interactions_1_1_audio_1_1_impact_audio_source_base.html',1,'Impact::Interactions::Audio']]],
  ['impactcollisionsinglecontactwrapper_20',['ImpactCollisionSingleContactWrapper',['../struct_impact_1_1_impact_collision_single_contact_wrapper.html',1,'Impact.ImpactCollisionSingleContactWrapper'],['../struct_impact_1_1_impact_collision_single_contact_wrapper.html#a1f344607eb8baaca0c595373632a44e8',1,'Impact.ImpactCollisionSingleContactWrapper.ImpactCollisionSingleContactWrapper()']]],
  ['impactcollisiontrigger2d_21',['ImpactCollisionTrigger2D',['../class_impact_1_1_triggers_1_1_impact_collision_trigger2_d.html',1,'Impact::Triggers']]],
  ['impactcollisiontrigger3d_22',['ImpactCollisionTrigger3D',['../class_impact_1_1_triggers_1_1_impact_collision_trigger3_d.html',1,'Impact::Triggers']]],
  ['impactcollisiontriggerbase_23',['ImpactCollisionTriggerBase',['../class_impact_1_1_triggers_1_1_impact_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['impactcollisiontriggerbase_3c_20impactcollisionsinglecontactwrapper_2c_20impactcontactpoint_20_3e_24',['ImpactCollisionTriggerBase&lt; ImpactCollisionSingleContactWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['impactcollisiontriggerbase_3c_20impactcollisionwrapper_2c_20impactcontactpoint_20_3e_25',['ImpactCollisionTriggerBase&lt; ImpactCollisionWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['impactcollisiontriggerwithcooldown2d_26',['ImpactCollisionTriggerWithCooldown2D',['../class_impact_1_1_triggers_1_1_impact_collision_trigger_with_cooldown2_d.html',1,'Impact::Triggers']]],
  ['impactcollisiontriggerwithcooldown3d_27',['ImpactCollisionTriggerWithCooldown3D',['../class_impact_1_1_triggers_1_1_impact_collision_trigger_with_cooldown3_d.html',1,'Impact::Triggers']]],
  ['impactcollisionwrapper_28',['ImpactCollisionWrapper',['../struct_impact_1_1_impact_collision_wrapper.html',1,'Impact.ImpactCollisionWrapper'],['../struct_impact_1_1_impact_collision_wrapper.html#afc41646f9f9397d7a53c4b2f8a4e9e84',1,'Impact.ImpactCollisionWrapper.ImpactCollisionWrapper(Collision collision3D)'],['../struct_impact_1_1_impact_collision_wrapper.html#a13b678d9299d952f28d489c84f02e5fa',1,'Impact.ImpactCollisionWrapper.ImpactCollisionWrapper(Collision2D collision2D)']]],
  ['impactcontactpoint_29',['ImpactContactPoint',['../struct_impact_1_1_impact_contact_point.html',1,'Impact.ImpactContactPoint'],['../struct_impact_1_1_impact_contact_point.html#a1361adae8595febca06b4514bc01a498',1,'Impact.ImpactContactPoint.ImpactContactPoint(ContactPoint contact3D)'],['../struct_impact_1_1_impact_contact_point.html#a3664f4959c58a7c915bbeee7da5d23b3',1,'Impact.ImpactContactPoint.ImpactContactPoint(ContactPoint2D contact2D)']]],
  ['impactdebugger_30',['ImpactDebugger',['../class_impact_1_1_impact_debugger.html',1,'Impact']]],
  ['impactdecal_31',['ImpactDecal',['../class_impact_1_1_interactions_1_1_decals_1_1_impact_decal.html',1,'Impact::Interactions::Decals']]],
  ['impactdecalbase_32',['ImpactDecalBase',['../class_impact_1_1_interactions_1_1_decals_1_1_impact_decal_base.html',1,'Impact::Interactions::Decals']]],
  ['impactdecalinteraction_33',['ImpactDecalInteraction',['../class_impact_1_1_interactions_1_1_decals_1_1_impact_decal_interaction.html',1,'Impact::Interactions::Decals']]],
  ['impactdecalmanager_34',['ImpactDecalManager',['../class_impact_1_1_interactions_1_1_decals_1_1_impact_decal_manager.html',1,'Impact::Interactions::Decals']]],
  ['impactdecalpool_35',['ImpactDecalPool',['../class_impact_1_1_interactions_1_1_decals_1_1_impact_decal_pool.html',1,'Impact::Interactions::Decals']]],
  ['impactinteractionbase_36',['ImpactInteractionBase',['../class_impact_1_1_interactions_1_1_impact_interaction_base.html',1,'Impact::Interactions']]],
  ['impactinteractionutilities_37',['ImpactInteractionUtilities',['../class_impact_1_1_interactions_1_1_impact_interaction_utilities.html',1,'Impact::Interactions']]],
  ['impactmanager_38',['ImpactManager',['../class_impact_1_1_impact_manager.html',1,'Impact']]],
  ['impactmanagerinstance_39',['ImpactManagerInstance',['../class_impact_1_1_impact_manager_instance.html',1,'Impact']]],
  ['impactmaterial_40',['ImpactMaterial',['../class_impact_1_1_materials_1_1_impact_material.html',1,'Impact::Materials']]],
  ['impactmaterialbase_41',['ImpactMaterialBase',['../class_impact_1_1_materials_1_1_impact_material_base.html',1,'Impact::Materials']]],
  ['impactmaterialcomposition_42',['ImpactMaterialComposition',['../struct_impact_1_1_impact_material_composition.html',1,'Impact.ImpactMaterialComposition'],['../struct_impact_1_1_impact_material_composition.html#a479a64b28f47896924e7ded04aaf41be',1,'Impact.ImpactMaterialComposition.ImpactMaterialComposition()']]],
  ['impactmaterialinteractionset_43',['ImpactMaterialInteractionSet',['../class_impact_1_1_materials_1_1_impact_material_interaction_set.html',1,'Impact::Materials']]],
  ['impactobjectbase_44',['ImpactObjectBase',['../class_impact_1_1_objects_1_1_impact_object_base.html',1,'Impact::Objects']]],
  ['impactobjectrigidbody_45',['ImpactObjectRigidbody',['../class_impact_1_1_objects_1_1_impact_object_rigidbody.html',1,'Impact::Objects']]],
  ['impactobjectrigidbodycheap_46',['ImpactObjectRigidbodyCheap',['../class_impact_1_1_objects_1_1_impact_object_rigidbody_cheap.html',1,'Impact::Objects']]],
  ['impactobjectrigidbodychild_47',['ImpactObjectRigidbodyChild',['../class_impact_1_1_objects_1_1_impact_object_rigidbody_child.html',1,'Impact::Objects']]],
  ['impactobjectsinglematerial_48',['ImpactObjectSingleMaterial',['../class_impact_1_1_objects_1_1_impact_object_single_material.html',1,'Impact::Objects']]],
  ['impactontriggerenter2d_49',['ImpactOnTriggerEnter2D',['../class_impact_1_1_triggers_1_1_impact_on_trigger_enter2_d.html',1,'Impact::Triggers']]],
  ['impactontriggerenter3d_50',['ImpactOnTriggerEnter3D',['../class_impact_1_1_triggers_1_1_impact_on_trigger_enter3_d.html',1,'Impact::Triggers']]],
  ['impactontriggerstay2d_51',['ImpactOnTriggerStay2D',['../class_impact_1_1_triggers_1_1_impact_on_trigger_stay2_d.html',1,'Impact::Triggers']]],
  ['impactontriggerstay3d_52',['ImpactOnTriggerStay3D',['../class_impact_1_1_triggers_1_1_impact_on_trigger_stay3_d.html',1,'Impact::Triggers']]],
  ['impactparticlecollisiontrigger_53',['ImpactParticleCollisionTrigger',['../class_impact_1_1_triggers_1_1_impact_particle_collision_trigger.html',1,'Impact::Triggers']]],
  ['impactparticleinteraction_54',['ImpactParticleInteraction',['../class_impact_1_1_interactions_1_1_particles_1_1_impact_particle_interaction.html',1,'Impact::Interactions::Particles']]],
  ['impactparticlepool_55',['ImpactParticlePool',['../class_impact_1_1_interactions_1_1_particles_1_1_impact_particle_pool.html',1,'Impact::Interactions::Particles']]],
  ['impactparticles_56',['ImpactParticles',['../class_impact_1_1_interactions_1_1_particles_1_1_impact_particles.html',1,'Impact::Interactions::Particles']]],
  ['impactparticlesbase_57',['ImpactParticlesBase',['../class_impact_1_1_interactions_1_1_particles_1_1_impact_particles_base.html',1,'Impact::Interactions::Particles']]],
  ['impactphysicmaterialmapping_58',['ImpactPhysicMaterialMapping',['../class_impact_1_1_impact_physic_material_mapping.html',1,'Impact']]],
  ['impactphysicsmaterial2dmapping_59',['ImpactPhysicsMaterial2DMapping',['../class_impact_1_1_impact_physics_material2_d_mapping.html',1,'Impact']]],
  ['impactraycasttrigger_60',['ImpactRaycastTrigger',['../class_impact_1_1_triggers_1_1_impact_raycast_trigger.html',1,'Impact::Triggers']]],
  ['impactrigidbodywrapper_61',['ImpactRigidbodyWrapper',['../class_impact_1_1_impact_rigidbody_wrapper.html',1,'Impact.ImpactRigidbodyWrapper'],['../class_impact_1_1_impact_rigidbody_wrapper.html#aef04516cf775c699e98c44ef94be938b',1,'Impact.ImpactRigidbodyWrapper.ImpactRigidbodyWrapper(GameObject gameObject)'],['../class_impact_1_1_impact_rigidbody_wrapper.html#a96dd0df84635082bd342053068fb0341',1,'Impact.ImpactRigidbodyWrapper.ImpactRigidbodyWrapper(Rigidbody rigidbody3D)'],['../class_impact_1_1_impact_rigidbody_wrapper.html#a424243b1b38b7602d55e608f174ca198',1,'Impact.ImpactRigidbodyWrapper.ImpactRigidbodyWrapper(Rigidbody2D rigidbody2D)']]],
  ['impactsimplecollisiontrigger2d_62',['ImpactSimpleCollisionTrigger2D',['../class_impact_1_1_triggers_1_1_impact_simple_collision_trigger2_d.html',1,'Impact::Triggers']]],
  ['impactsimplecollisiontrigger3d_63',['ImpactSimpleCollisionTrigger3D',['../class_impact_1_1_triggers_1_1_impact_simple_collision_trigger3_d.html',1,'Impact::Triggers']]],
  ['impactslideandrolltrigger2d_64',['ImpactSlideAndRollTrigger2D',['../class_impact_1_1_triggers_1_1_impact_slide_and_roll_trigger2_d.html',1,'Impact::Triggers']]],
  ['impactslideandrolltrigger3d_65',['ImpactSlideAndRollTrigger3D',['../class_impact_1_1_triggers_1_1_impact_slide_and_roll_trigger3_d.html',1,'Impact::Triggers']]],
  ['impactslideandrolltriggerbase_66',['ImpactSlideAndRollTriggerBase',['../class_impact_1_1_triggers_1_1_impact_slide_and_roll_trigger_base.html',1,'Impact::Triggers']]],
  ['impactslideandrolltriggerbase_3c_20impactcollisionsinglecontactwrapper_2c_20impactcontactpoint_20_3e_67',['ImpactSlideAndRollTriggerBase&lt; ImpactCollisionSingleContactWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_slide_and_roll_trigger_base.html',1,'Impact::Triggers']]],
  ['impactslideandrolltriggerbase_3c_20impactcollisionwrapper_2c_20impactcontactpoint_20_3e_68',['ImpactSlideAndRollTriggerBase&lt; ImpactCollisionWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_slide_and_roll_trigger_base.html',1,'Impact::Triggers']]],
  ['impactspeculativecollisiontrigger2d_69',['ImpactSpeculativeCollisionTrigger2D',['../class_impact_1_1_triggers_1_1_impact_speculative_collision_trigger2_d.html',1,'Impact::Triggers']]],
  ['impactspeculativecollisiontrigger3d_70',['ImpactSpeculativeCollisionTrigger3D',['../class_impact_1_1_triggers_1_1_impact_speculative_collision_trigger3_d.html',1,'Impact::Triggers']]],
  ['impactspeculativecollisiontriggerbase_71',['ImpactSpeculativeCollisionTriggerBase',['../class_impact_1_1_triggers_1_1_impact_speculative_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['impactspeculativecollisiontriggerbase_3c_20impactcollisionwrapper_2c_20impactcontactpoint_20_3e_72',['ImpactSpeculativeCollisionTriggerBase&lt; ImpactCollisionWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_speculative_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['impacttag_73',['ImpactTag',['../struct_impact_1_1_impact_tag.html',1,'Impact.ImpactTag'],['../struct_impact_1_1_impact_tag.html#adff48b91f9283a61012adffa4837098a',1,'Impact.ImpactTag.ImpactTag()']]],
  ['impacttaglibrary_74',['ImpactTagLibrary',['../class_impact_1_1_tag_library_1_1_impact_tag_library.html',1,'Impact::TagLibrary']]],
  ['impacttaglibrarybase_75',['ImpactTagLibraryBase',['../class_impact_1_1_tag_library_1_1_impact_tag_library_base.html',1,'Impact::TagLibrary']]],
  ['impacttaglibraryconstants_76',['ImpactTagLibraryConstants',['../class_impact_1_1_tag_library_1_1_impact_tag_library_constants.html',1,'Impact::TagLibrary']]],
  ['impacttaglibraryextensions_77',['ImpactTagLibraryExtensions',['../class_impact_1_1_tag_library_1_1_impact_tag_library_extensions.html',1,'Impact::TagLibrary']]],
  ['impacttagmask_78',['ImpactTagMask',['../struct_impact_1_1_impact_tag_mask.html',1,'Impact.ImpactTagMask'],['../struct_impact_1_1_impact_tag_mask.html#a2502df11cadb365195d2f832a701bd0b',1,'Impact.ImpactTagMask.ImpactTagMask()']]],
  ['impactterrain_79',['ImpactTerrain',['../class_impact_1_1_objects_1_1_impact_terrain.html',1,'Impact::Objects']]],
  ['impacttriggerbase_80',['ImpactTriggerBase',['../class_impact_1_1_triggers_1_1_impact_trigger_base.html',1,'Impact::Triggers']]],
  ['impacttriggerbase_3c_20impactcollisionwrapper_2c_20impactcontactpoint_20_3e_81',['ImpactTriggerBase&lt; ImpactCollisionWrapper, ImpactContactPoint &gt;',['../class_impact_1_1_triggers_1_1_impact_trigger_base.html',1,'Impact::Triggers']]],
  ['impacttriggercontactmode_82',['ImpactTriggerContactMode',['../namespace_impact_1_1_triggers.html#a9bae7f8770fde6ebf32863b5dfaff84f',1,'Impact::Triggers']]],
  ['impactvelocitycollisiontrigger2d_83',['ImpactVelocityCollisionTrigger2D',['../class_impact_1_1_triggers_1_1_impact_velocity_collision_trigger2_d.html',1,'Impact::Triggers']]],
  ['impactvelocitycollisiontrigger3d_84',['ImpactVelocityCollisionTrigger3D',['../class_impact_1_1_triggers_1_1_impact_velocity_collision_trigger3_d.html',1,'Impact::Triggers']]],
  ['impactvelocitycollisiontriggerbase_85',['ImpactVelocityCollisionTriggerBase',['../class_impact_1_1_triggers_1_1_impact_velocity_collision_trigger_base.html',1,'Impact::Triggers']]],
  ['includetagsfilter_86',['IncludeTagsFilter',['../class_impact_1_1_materials_1_1_impact_material_interaction_set.html#a1bb15d7646a293a9bd70bdc85264bf98',1,'Impact::Materials::ImpactMaterialInteractionSet']]],
  ['incrementphysicsinteractionslimit_87',['IncrementPhysicsInteractionsLimit',['../class_impact_1_1_impact_manager.html#a8662b7ce0aaaec508de79538243d301d',1,'Impact.ImpactManager.IncrementPhysicsInteractionsLimit()'],['../class_impact_1_1_impact_manager_instance.html#a6bcbf68c578ce039d1d433c7a35af4b3',1,'Impact.ImpactManagerInstance.IncrementPhysicsInteractionsLimit()']]],
  ['indexof_3c_20t_20_3e_88',['IndexOf&lt; T &gt;',['../class_impact_1_1_utility_1_1_extensions.html#a75286c54ac13cd334e971d2978d8dedd',1,'Impact::Utility::Extensions']]],
  ['initialize_89',['Initialize',['../class_impact_1_1_utility_1_1_object_pool_1_1_object_pool.html#ac46632f435b6d413e9a6f69fc48c909b',1,'Impact.Utility.ObjectPool.ObjectPool.Initialize()'],['../class_impact_1_1_impact_manager.html#aaff37fc2b4e923254c5593d0c2c4ca7b',1,'Impact.ImpactManager.Initialize()']]],
  ['interaction_90',['Interaction',['../class_impact_1_1_interactions_1_1_audio_1_1_audio_interaction_result.html#a583578ef5136c7762f6ac048daa1a9df',1,'Impact::Interactions::Audio::AudioInteractionResult']]],
  ['interactioncount_91',['InteractionCount',['../class_impact_1_1_materials_1_1_impact_material_interaction_set.html#a4cffe0a3ca5c970e884eb629dadd4d2d',1,'Impact::Materials::ImpactMaterialInteractionSet']]],
  ['interactiondata_92',['InteractionData',['../struct_impact_1_1_interaction_data.html',1,'Impact']]],
  ['interactiondatautilities_93',['InteractionDataUtilities',['../class_impact_1_1_interaction_data_utilities.html',1,'Impact']]],
  ['interactionintervaltype_94',['InteractionIntervalType',['../namespace_impact_1_1_interactions.html#a9b11bf6439df02144e11270b78a77a73',1,'Impact::Interactions']]],
  ['interactionresultbuffer_95',['InteractionResultBuffer',['../class_impact_1_1_impact_manager_instance.html#a1e98f6fbac1ba0e73b0c7893e30287c2',1,'Impact.ImpactManagerInstance.InteractionResultBuffer()'],['../class_impact_1_1_impact_manager.html#a931a2d21f0eef363bbb639a6008565ce',1,'Impact.ImpactManager.InteractionResultBuffer()']]],
  ['interactionresultextensions_96',['InteractionResultExtensions',['../class_impact_1_1_interactions_1_1_interaction_result_extensions.html',1,'Impact::Interactions']]],
  ['interactions_97',['Interactions',['../namespace_impact_1_1_interactions.html',1,'Impact']]],
  ['interactiontype_98',['InteractionType',['../struct_impact_1_1_interaction_data.html#a76e4578b8e8fd8ce6a58b9d491a16a0d',1,'Impact.InteractionData.InteractionType()'],['../interface_impact_1_1_i_interaction_data.html#a53fe3a9b437dbebce892efa78c864906',1,'Impact.IInteractionData.InteractionType()']]],
  ['interactiontypecollision_99',['InteractionTypeCollision',['../struct_impact_1_1_interaction_data.html#a1b46a390c728366cb8799b39953b1ecd',1,'Impact::InteractionData']]],
  ['interactiontyperoll_100',['InteractionTypeRoll',['../struct_impact_1_1_interaction_data.html#a30313ef09deda3ecb1105215adc9ec1e',1,'Impact::InteractionData']]],
  ['interactiontypesimple_101',['InteractionTypeSimple',['../struct_impact_1_1_interaction_data.html#abbaaa37ad4c60e4a672b15461ddd4421',1,'Impact::InteractionData']]],
  ['interactiontypeslide_102',['InteractionTypeSlide',['../struct_impact_1_1_interaction_data.html#a0a9c8f31e70519ff1279f577d819c864',1,'Impact::InteractionData']]],
  ['introduction_103',['Introduction',['../index.html',1,'']]],
  ['ipoolable_104',['IPoolable',['../interface_impact_1_1_utility_1_1_object_pool_1_1_i_poolable.html',1,'Impact::Utility::ObjectPool']]],
  ['isalive_105',['IsAlive',['../class_impact_1_1_interactions_1_1_audio_1_1_audio_interaction_result.html#a8c85700ba282eec7e2b255e5e95ae3b6',1,'Impact.Interactions.Audio.AudioInteractionResult.IsAlive()'],['../class_impact_1_1_interactions_1_1_decals_1_1_decal_interaction_result.html#add28a4fae6de78b03e4bb804e5d4685c',1,'Impact.Interactions.Decals.DecalInteractionResult.IsAlive()'],['../interface_impact_1_1_interactions_1_1_i_continuous_interaction_result.html#a4a8b5a337967db645cc140a95d65b7d2',1,'Impact.Interactions.IContinuousInteractionResult.IsAlive()'],['../class_impact_1_1_interactions_1_1_particles_1_1_particle_interaction_result.html#abb61bad78d5c18c65a8b191b9f1e9bfd',1,'Impact.Interactions.Particles.ParticleInteractionResult.IsAlive()']]],
  ['isavailable_106',['IsAvailable',['../class_impact_1_1_utility_1_1_object_pool_1_1_pooled_object.html#a7c390c0865e2015c8395296ccbcfc8ba',1,'Impact::Utility::ObjectPool::PooledObject']]],
  ['isbitset_107',['IsBitSet',['../class_impact_1_1_utility_1_1_extensions.html#ad58912ca333218f5920826418a83f7e1',1,'Impact::Utility::Extensions']]],
  ['isinrange_108',['IsInRange',['../struct_impact_1_1_utility_1_1_range.html#a1ea0a83105f573ac9bf4b779d21741de',1,'Impact::Utility::Range']]],
  ['isparticlelooped_109',['IsParticleLooped',['../class_impact_1_1_interactions_1_1_particles_1_1_impact_particle_interaction.html#ad63756ef06582ac79c2e5e6c63478a0f',1,'Impact.Interactions.Particles.ImpactParticleInteraction.IsParticleLooped()'],['../class_impact_1_1_interactions_1_1_particles_1_1_particle_interaction_result.html#add9a04588fe7935ce4baabeff3e8cb2b',1,'Impact.Interactions.Particles.ParticleInteractionResult.IsParticleLooped()']]],
  ['isvalid_110',['IsValid',['../class_impact_1_1_interactions_1_1_decals_1_1_decal_interaction_result.html#ad13d68f33ed061eaeff098c0fa837cac',1,'Impact.Interactions.Decals.DecalInteractionResult.IsValid()'],['../interface_impact_1_1_interactions_1_1_i_interaction_result.html#a77ca26f6b0fad53a152c11ba2865dbed',1,'Impact.Interactions.IInteractionResult.IsValid()'],['../class_impact_1_1_interactions_1_1_particles_1_1_particle_interaction_result.html#ad9002108335a5054aa8d34410cc4d60b',1,'Impact.Interactions.Particles.ParticleInteractionResult.IsValid()'],['../class_impact_1_1_interactions_1_1_audio_1_1_audio_interaction_result.html#a02854c071a8921b5a5123244f903b73c',1,'Impact.Interactions.Audio.AudioInteractionResult.IsValid()']]],
  ['materials_111',['Materials',['../namespace_impact_1_1_materials.html',1,'Impact']]],
  ['objectpool_112',['ObjectPool',['../namespace_impact_1_1_utility_1_1_object_pool.html',1,'Impact::Utility']]],
  ['objects_113',['Objects',['../namespace_impact_1_1_objects.html',1,'Impact']]],
  ['particles_114',['Particles',['../namespace_impact_1_1_interactions_1_1_particles.html',1,'Impact::Interactions']]],
  ['taglibrary_115',['TagLibrary',['../namespace_impact_1_1_tag_library.html',1,'Impact']]],
  ['triggers_116',['Triggers',['../namespace_impact_1_1_triggers.html',1,'Impact']]],
  ['utility_117',['Utility',['../namespace_impact_1_1_utility.html',1,'Impact']]]
];
